<?php

class Hash {

    public static function make($string)
    {
        return password_hash($string, PASSWORD_DEFAULT);
    }

    public static function verify($hashed, $string)
    {
        return (password_verify($string, $hashed));
    }

    public static function unique()
    {
        return self::make(uniqid());
    }

    /*
     * WHY WE CANT USE THE BELOW METHODS:
     * Warning
    The salt option has been deprecated as of PHP 7.0.0.
    It is now preferred to simply use the salt
    that is generated by default.

    public static function make($string, $salt = '') {
        return hash('sha256', $string.$salt);
    }

    public static function salt($length){
        return openssl_random_pseudo_bytes($length);
    }


    */
}